import { Router, type IRouter } from "express";
import healthRouter from "./health";
import productsRouter from "./products";
import storesRouter from "./stores";
import storeTypesRouter from "./storeTypes";
import storageRouter from "./storage";
import adminRouter from "./admin";
import categoriesRouter from "./categories";
import ordersRouter from "./orders";
import customersRouter from "./customers";
import authRouter from "./auth";
import addressesRouter from "./addresses";
import notificationsRouter from "./notifications";
import broadcastsRouter from "./broadcasts";
import refundsRouter from "./refunds";
import deliveryDriversRouter from "./deliveryDrivers";
import ratingsRouter from "./ratings";
import walletRouter from "./wallet";
import referralRouter from "./referral";

const router: IRouter = Router();

router.use(adminRouter);
router.use(healthRouter);
router.use(productsRouter);
router.use(storesRouter);
router.use(storeTypesRouter);
router.use(categoriesRouter);
router.use(storageRouter);
router.use(ordersRouter);
router.use(customersRouter);
router.use(authRouter);
router.use(addressesRouter);
router.use(notificationsRouter);
router.use(broadcastsRouter);
router.use(refundsRouter);
router.use(deliveryDriversRouter);
router.use(ratingsRouter);
router.use(walletRouter);
router.use(referralRouter);

export default router;
